/**
 * LoadingState Component Unit Tests
 * 
 * This test file validates the LoadingState component which displays a skeleton
 * loading animation while the AI is generating a weekend plan.
 * 
 * Test Coverage (3 test cases as per specification):
 * 1. Renders skeleton/pulse animation elements - Verifies visual loading feedback
 * 2. Displays "Creating your perfect weekend..." message - Verifies status text
 * 3. Has aria-busy="true" for accessibility - Verifies WCAG compliance
 * 
 * @module __tests__/components/LoadingState.test
 */

import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { LoadingState } from '../../components/LoadingState';

/**
 * Test suite for LoadingState component
 * 
 * The LoadingState component is a pure presentational component with:
 * - Multiple skeleton cards with pulse animation
 * - A loading status message
 * - Proper accessibility attributes for screen readers
 */
describe('LoadingState', () => {
  /**
   * Test Case 1: Renders skeleton/pulse animation elements
   * 
   * Verifies that the component renders skeleton elements with the
   * Tailwind CSS animate-pulse class to provide visual loading feedback.
   * The component should contain multiple animated placeholder elements
   * that simulate the structure of the expected plan output.
   */
  it('renders skeleton/pulse animation elements', () => {
    // Arrange & Act: Render the LoadingState component
    const { container } = render(<LoadingState />);

    // Assert: Verify skeleton elements with animate-pulse class are present
    const skeletonElements = container.querySelectorAll('.animate-pulse');
    
    // The component should have multiple skeleton elements (headers and content lines)
    // Based on the component structure, there are 4 cards with multiple skeleton bars each
    expect(skeletonElements.length).toBeGreaterThan(0);
    
    // Verify we have a significant number of skeleton elements for proper visual feedback
    // Each skeleton card has header + content lines with animate-pulse
    expect(skeletonElements.length).toBeGreaterThanOrEqual(10);

    // Verify skeleton elements have proper styling (bg-gray-200 for skeleton appearance)
    const firstSkeleton = skeletonElements[0];
    expect(firstSkeleton).toHaveClass('bg-gray-200');
    expect(firstSkeleton).toHaveClass('rounded');
  });

  /**
   * Test Case 2: Displays "Creating your perfect weekend..." message
   * 
   * Verifies that the loading status message is displayed to inform users
   * that their weekend plan is being generated by the AI.
   * Uses case-insensitive regex for robustness.
   */
  it('displays "Creating your perfect weekend..." message', () => {
    // Arrange & Act: Render the LoadingState component
    render(<LoadingState />);

    // Assert: Verify the loading message is displayed in the document
    const loadingMessage = screen.getByText(/creating your perfect weekend/i);
    expect(loadingMessage).toBeInTheDocument();
    
    // Verify the message has proper styling for visibility
    expect(loadingMessage).toHaveClass('text-lg');
    expect(loadingMessage).toHaveClass('text-center');
  });

  /**
   * Test Case 3: Has aria-busy="true" for accessibility
   * 
   * Verifies WCAG compliance by ensuring the loading container has
   * aria-busy="true" to inform assistive technologies that content
   * is being loaded. This is critical for screen reader users.
   */
  it('has aria-busy="true" for accessibility', () => {
    // Arrange & Act: Render the LoadingState component
    render(<LoadingState />);

    // Assert: Find the element with role="status" (semantic loading indicator)
    const statusElement = screen.getByRole('status');
    expect(statusElement).toBeInTheDocument();
    
    // Verify aria-busy attribute is set to "true"
    expect(statusElement).toHaveAttribute('aria-busy', 'true');
    
    // Also verify the aria-label is present for screen reader context
    expect(statusElement).toHaveAttribute('aria-label', 'Loading weekend plan');
  });
});
